### ISSUE TITLE
Can't get Cmd to recognize "$" as a command...

### ISSUE THREAD

**Issue by DarkPygmy** [PacktPublishing/Learn-C-Programming-Second-Edition#1]
I set the environmental variables to include the cygwin64 directory yet it still isn't working...

**Comment by shruthis-shetty** [comment]
Hi @DarkPygmy , Can you share the screenshot of the error you're getting?
This would be helpful for us to know what exactly the error is

**Comment by jeffszuhay** [comment]
Not enough info from user to resolve this issue.
